name: CICD

on:
 workflow_dispatch:

jobs:
  code:
   runs-on: ubuntu-latest
   steps:
    - name: Clone the code
      run: echo "Cloning the code"
  build:
     runs-on: ubuntu-latest
     steps:
      - name: Build using the docker
        run: echo "Build using the docker background"

  test:
     runs-on: ubuntu-latest
     steps:
      - name: Running test cases
        run: echo "Ruuning test"

  deploy:
     runs-on: ubuntu-latest
     steps:
      - name: deploying on the machine
        run: echo "Deployed"
     
